using System.Collections;
using System.Collections.Generic;
using UnityEngine;  //Everything above this line was automatically generated by Unity
using UnityEngine.SceneManagement; //needed to change scenes

public class changeScene : MonoBehaviour
{
    //get access to a game object in script
    public GameObject changeSceneButton; //this is the sprite
    public string otherScene; //the other scene

    void OnMouseDown(){
        Debug.Log("Box sprite clicked. Changing scene.");
        SceneManager.LoadScene(otherScene);
    }
}
