using System.Collections;
using System.Collections.Generic;
using UnityEngine;//everything including this line and above was automatically generated by Unity

//have camera follow player in hall (but only on x axis)
public class followPlayer : MonoBehaviour
{
    public Transform player;
    public Vector3 offset;
    private Vector3 cameraPos;

    // Update is called once per frame
    void Update()
    {
        cameraPos = transform.position; //transform.position refers to camera object
        cameraPos.y= (player.position).y;
        transform.position = cameraPos;
    }
}
